// apps/portfolio/src/App.vue
<script setup lang="ts">
</script>

<template>
  <div data-testid='app'>
      <h1 data-testid='app-title'>Ben Turner</h1>
      <h2>Salt Lake City, Utah</h2>
      <h3>Senior Frontend Developer</h3>
          <a href="https://territories.ai" target="__blank">Territories.ai</a>
      <ul>
        <li>
          <a href="https://github.com/bbgrabbag" target="__blank">GitHub</a>
        </li>
        <li>
          <a href="https://linkedin.com/in/ben-b-turner" target="__blank">LinkedIn</a>
        </li>
      </ul>
    </div>
</template>

<style scoped>
</style>

// client/src/App.tsx
export const App = () => {
  return (
    <div data-testid='app'>
      <h1 data-testid='app-title'>Ben Turner</h1>
      <h3>Senior Software Engineer</h3>
          <a href="https://territories.ai" target="__blank">Territories.ai</a>
      <ul>
        <li>
          <a href="https://github.com/bbgrabbag" target="__blank">GitHub</a>
        </li>
        <li>
          <a href="https://linkedin.com/in/ben-b-turner" target="__blank">LinkedIn</a>
        </li>
      </ul>
    </div>
  )
}
